#! /bin/sh
#================================================
#
#
#	██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#	██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#	██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#	██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#	██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#	╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#
#================================================

$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
numlockx &

bspc monitor -d 1 2 3 4 5 6 7 8 9 G

bspc config border_width          1
bspc config window_gap            7

bspc config normal_border_color   "#000000"
bspc config active_border_color   "#000000"
bspc config focused_border_color  "#ffffff"
bspc config presel_feedback_color "#23252e"

bspc config focus_follows_pointer true
bspc config pointer_modifier	  super

bspc config split_ratio           0.5

bspc config single_monocle	      true

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle	  true
